[package]
name = "ross-mount"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nix = { version = "0.29", features = ["mount", "fs"] }
thiserror = "2"
tracing = "0.1"
