[package]
name = "ross-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
prost = "0.13"
prost-types = "0.13"
tonic = "0.12"
serde = { version = "1", features = ["derive"] }

[build-dependencies]
tonic-build = "0.12"
